### ISSUE TITLE
Crash when Start button is clicked

### ISSUE THREAD

**Issue by GuiTheDev** [Seeroy/kubek-minecraft-dashboard#1]
Crashes when Start button is clicked

[22:42:29] Kubek listening on http://localhost:3000
[22:42:34] GET /kubek/version
[22:42:34] GET /server/publicIP?server=null
[22:42:34] GET /servers/list
[22:42:35] GET /cores/list
[22:42:35] GET /cores/spigot/list
[22:42:35] GET /kubek/version
[22:42:36] GET /server/publicIP?server=minerp
[22:42:36] GET /servers/list
[22:42:36] GET /cores/list
[22:42:36] GET /cores/spigot/list
[22:42:42] GET /server/start?server=minerp
[22:42:42] STARTING SERVER: minerp
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn "servers/minerp/start.sh" ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
root@minecraft:/home/gui/kubek-minecraft-dashboard#

**Comment by Seeroy** [comment]
thanks i will fix it in the next update

**Comment by Seeroy** [comment]
Thanks. i will fix it in the next update

**Comment by ZEdasmoscas** [comment]
When is the new update expected to be released?

**Comment by Seeroy** [comment]
I think 1-2 days. But you can try to recreate server:
- Close Kubek
- Delete "servers" directory in the same directory as Kubek
- Start Kubek and create new server

**Comment by nisel11** [comment]
same problem on latest version. I will not throw off the logs because they are the same as those of GuiTheDev

**Comment by Seeroy** [comment]
> same problem on latest version. I will not throw off the logs because they are the same as those of GuiTheDev

Hello. What operating system do you have? If you recreate everything, does the error persist?

**Comment by nisel11** [comment]
Arch linux. No, recreating the server did not help, I reinstalled the operating system, but the problem did not change

**Comment by GuiTheDev** [comment]
Yeah re-creating the server didnt work for me either i just made my own thingy

**Comment by Seeroy** [comment]
In what folder is the Kubek (full path)?

**Comment by Seeroy** [comment]
Sorry for the long wait. Fixed in this release: https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v1.1.6

**Comment by GuiTheDev** [comment]
Thanks
