### ISSUE TITLE
после установки сервера, перезапуска проги - получаю следующее сообщение:

### ISSUE THREAD

**Issue by Urubamba77** [Seeroy/kubek-minecraft-dashboard#17]
ReferenceError: authsucc is not defined
    at C:\snapshot\kubek-minecraft-dashboard\app.js
    at Layer.handle [as handle_request] (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:323:13)
    at C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:341:12)
    at next (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:275:10)
    at cookieParser (C:\snapshot\kubek-minecraft-dashboard\node_modules\cookie-parser\index.js:57:14)
    at Layer.handle [as handle_request] (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:323:13)
    at C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:284:7

**Comment by Urubamba77** [comment]
Kubek v1.1.1
https://github.com/Seeroy/kubek-minecraft-dashboard

Updates found! URL:
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v1.2.14

[11:20:27] Kubek listening on http://localhost:3000
ReferenceError: authsucc is not defined
    at C:\snapshot\kubek-minecraft-dashboard\app.js
    at Layer.handle [as handle_request] (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:323:13)
    at C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:341:12)
    at next (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:275:10)
    at cookieParser (C:\snapshot\kubek-minecraft-dashboard\node_modules\cookie-parser\index.js:57:14)
    at Layer.handle [as handle_request] (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:323:13)
    at C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:284:7

**Comment by BasToTheMax** [comment]
Try to update to the latest version

**Comment by Urubamba77** [comment]
I have download the latest version today from here

**Comment by Urubamba77** [comment]
![2022-07-27_11-41-27](https://user-images.githubusercontent.com/110091396/181205234-53b8c13e-3811-43e9-abb5-138e62c00f42.png)
![2022-07-27_11-39-01](https://user-images.githubusercontent.com/110091396/181205275-e75df1af-aa3f-493f-bbc4-60a013dc228f.png)

**Comment by Urubamba77** [comment]
![image](https://user-images.githubusercontent.com/110091396/181205602-091cf02a-0b41-4689-9434-80e6c305b9ea.png)
![image](https://user-images.githubusercontent.com/110091396/181205761-727451c9-3b22-49a4-974d-1666a6f9866c.png)
Server downloading is good, but localhost not starting and error is happening

![image](https://user-images.githubusercontent.com/110091396/181206305-b4ab5ae9-d2f9-40c7-abf8-d16b1e6889d3.png)

**Comment by Seeroy** [comment]
Why are you using so old version? Download latest from here
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v1.2.14

**Comment by Urubamba77** [comment]
)) now it working. I was sure I have the last version. But I was wrong. Thanks a lot!
