### ISSUE TITLE
Start failed

### ISSUE THREAD

**Issue by DragonFire1230** [Seeroy/kubek-minecraft-dashboard#18]
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.readServersJSON (C:\snapshot\kubek-minecraft-dashboard\my_modules\config.js:32:17)
    at Object.<anonymous> (C:\snapshot\kubek-minecraft-dashboard\app.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:17:47

**Comment by DragonFire1230** [comment]
P.S: this is latest version

**Comment by Seeroy** [comment]
Delete "servers" directory and restart Kubek 
NOTE: All your servers in Kubek will be removed

**Comment by DragonFire1230** [comment]
Hello, thanks, it helped. Dashboard now works
