### ISSUE TITLE
#error

### ISSUE THREAD

**Issue by allfred1** [Seeroy/kubek-minecraft-dashboard#22]
Hi!

I did everything according to your README.MD but when I execute this happens:

nodejs v v12.22.9
ubuntu server 22.04

```

root@allfred:/home/allfred/kubek-minecraft-dashboard# node app.js


internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'cli-progress'
Require stack:
- /home/allfred/kubek-minecraft-dashboard/my_modules/updater.js
- /home/allfred/kubek-minecraft-dashboard/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/oldiberezko/kubek-minecraft-dashboard/my_modules/updater.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/allfred/kubek-minecraft-dashboard/my_modules/updater.js',
    '/home/allfred/kubek-minecraft-dashboard/app.js'
  ]
}
```

**Comment by Seeroy** [comment]
Hi. Try to install this module manually: npm i cli-progress

**Comment by allfred1** [comment]
again it


```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:child_process'
Require stack:
- /home/oldiberezko/kubek-minecraft-dashboard/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/oldiberezko/kubek-minecraft-dashboard/app.js:29:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/oldiberezko/kubek-minecraft-dashboard/app.js' ]
}
```

**Comment by BasToTheMax** [comment]
Use node 17 or newer

**Comment by Seeroy** [comment]
I think something bad with your NodeJS installation. Maybe your NodeJS is so old, try to update to 17 or better, as said @BasToTheMax
