### ISSUE TITLE
Unable to upload files

### ISSUE THREAD

**Issue by MattysLouw** [Seeroy/kubek-minecraft-dashboard#29]
This error happens when trying to upload a file into the server's directory. Kubek version is 2.0.9
```
ReferenceError: req is not defined
    at /mnt/disk2/kubek/routers/upload.js:148:43
    at Layer.handle [as handle_request] (/mnt/disk2/kubek/node_modules/express/lib/router/layer.js:95:5)
    at next (/mnt/disk2/kubek/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/mnt/disk2/kubek/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/mnt/disk2/kubek/node_modules/express/lib/router/layer.js:95:5)
    at /mnt/disk2/kubek/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/mnt/disk2/kubek/node_modules/express/lib/router/index.js:346:12)
    at next (/mnt/disk2/kubek/node_modules/express/lib/router/index.js:280:10)
    at /mnt/disk2/kubek/routers/upload.js:23:7
    at Layer.handle [as handle_request] (/mnt/disk2/kubek/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.0.10
Try it and close issue, if everything is alright

**Comment by MattysLouw** [comment]
Works fine now. Thank you.
