### ISSUE TITLE
Ошибка компиляции 

### ISSUE THREAD

**Issue by jadnast** [Seeroy/kubek-minecraft-dashboard#30]
Я скомпилировал в .exe немного переделаю версию (только изменил дизайн) и при запуске программа сразу же закрывается.
Я проверил через консоль и вылезает, такая ошибка: 

```pkg/prelude/bootstrap.js:438
  if (error) throw error;
             ^

Error: File 'C:\**\kubek-minecraft-dashboard-main\translations\ru.json' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:657:19)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:1046:29)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1094:18)
    at Object.translateHTML (C:\snapshot\kubek-minecraft-dashboard-main\my_modules\translator.js:5:19)
    at C:\snapshot\kubek-minecraft-dashboard-main\app.js:243:70
    at Request._callback (C:\snapshot\kubek-minecraft-dashboard-main\my_modules\updater.js:22:7)
    at Request.callback (C:\snapshot\kubek-minecraft-dashboard-main\node_modules\request\request.js:185:22)
    at Request.emit (node:events:537:28)
    at Request.<anonymous> (C:\snapshot\kubek-minecraft-dashboard-main\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:537:28) {
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\snapshot\\kubek-minecraft-dashboard-main\\translations\\ru.json',
  pkg: true
}

Node.js v18.5.0
```

Комилировал с помощью pkg

**Comment by Seeroy** [comment]
Попробуйте собирать используя файл конфигурации
`pkg --config pkgconfig.json app.js`

**Comment by jadnast** [comment]
Я скоипилировал, но теперь другая ошибка.
Когда я перебрысываю файл .exe на рабочий стол, то приложение отказывается работать.

Скомпилировал я другим способом, через package.json добавив в него настройки для pkg
```
  "pkg": {
    "scripts": [
      "my_modules/*",
      "node_modules/",
      "routers/*",
      "translations/*",
      "www/js/*",
      "www/pages/*.js",
      "config.json",
      "users.json"
    ],
    "assets": [
      "www/assets/**/*",
      "www/css/**/*",
      "www/css/*",
      "www/fonts/**/*",
      "www/pages/*.html",
      "www/pages/*.css",
      "www/*.html",
      "www/*.ico"
    ],
    "targets": [
      "node18-win"
    ]
  }
```
