### ISSUE TITLE
main ERROR Unable to locate appender "ServerGuiConsole" for logger config "root"

### ISSUE THREAD

**Issue by croziors** [Seeroy/kubek-minecraft-dashboard#93]
"/usr/kubek/binaries/java/8/jdk8u422-b05/bin/java" -Dfile.encoding=UTF-8 -Xmx16128M  -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -jar forge-1.12.2-14.23.5.2860.jar nogui

2024-09-07 01:26:38,407 main ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND
2024-09-07 01:26:38,478 main WARN Disabling terminal, you're running in an unsupported environment.
2024-09-07 01:26:38,562 main ERROR Unable to locate appender "ServerGuiConsole" for logger config "root"
[01:26:38] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[01:26:38] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[01:26:38] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/Lists
at net.minecraftforge.fml.common.launcher.FMLTweaker.acceptOptions(FMLTweaker.java:69)
at net.minecraftforge.fml.common.launcher.FMLServerTweaker.acceptOptions(FMLServerTweaker.java:36)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
... 6 more
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Lists
at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 10 more

The server was terminated forcibly

**Comment by Seeroy** [comment]
Sorry for long waiting. It looks like issue with Forge server installation. Maybe some files not exists
